#!/usr/bin/env bash

DEVROOT='../caribou-development'

rm resources/resource_package.zip

mkdir -p package/resources
rsync -av --safe-links --exclude $DEVROOT/target $DEVROOT/.gitignore $DEVROOT/app $DEVROOT/src $DEVROOT/project.clj package
rsync -av --safe-links $DEVROOT/resources/ package/resources

for BASEDIR in admin api site
do
    rm -rf package/$BASEDIR/target package/$BASEDIR/test
done

for CONFIGFILE in boot production staging development test
do
    sed -i '' 's/caribou_/$safeproject$_/g' package/resources/config/$CONFIGFILE.clj
    sed -i '' 's/skel.controllers/$project$.controllers/g' package/resources/config/$CONFIGFILE.clj
    sed -i '' 's/skel.hooks/$project$.hooks/g' package/resources/config/$CONFIGFILE.clj
    sed -i '' 's/skel.fields/$project$.fields/g' package/resources/config/$CONFIGFILE.clj
done

sed -i '' 's/skel.hooks.model/$project$.hooks.model/g' package/src/skel/hooks/model.clj
sed -i '' 's/skel.migrations.default/$project$.migrations.default/g' package/src/skel/migrations/default.clj
sed -i '' 's/skel.migrations.order/$project$.migrations.order/g' package/src/skel/migrations/order.clj
sed -i '' 's/skel.controllers/$project$.controllers/g' package/src/skel/controllers/home.clj
sed -i '' 's/skel.core/$project$.core/g' package/src/immutant/init.clj
sed -i '' 's/skel.core/$project$.core/g' package/src/skel/core.clj

sed -i '' 's/caribou-devsite/$project$/g' package/project.clj
sed -i '' 's/skel.core/$project$.core/g' package/project.clj
sed -i '' 's/skel.migrations/$project$.migrations/g' package/project.clj
sed -i '' 's/caribou-development-frontend/$project$-frontend/g' package/project.clj

sed -i '' 's/my-test/$project$/g' package/resources/templates/home.html
sed -i '' 's/skel/$project$/g' package/resources/templates/home.html

pushd .
cd package
zip -vr ../resources/resource_package.zip *
popd

rm -rf package
